# Generated by Django 5.1 on 2024-09-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_student_address_remove_student_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
